version: '3.8'

services:
  nft-market-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_CCY_TOKEN_ADDRESS=${NEXT_PUBLIC_CCY_TOKEN_ADDRESS}
        - NEXT_PUBLIC_RPC_URL=${NEXT_PUBLIC_RPC_URL}
    container_name: nft-market-web
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CCY_TOKEN_ADDRESS=${NEXT_PUBLIC_CCY_TOKEN_ADDRESS}
      - NEXT_PUBLIC_RPC_URL=${NEXT_PUBLIC_RPC_URL}
      - CCY_TOKEN_ADMIN_PRIVATE_KEY=${CCY_TOKEN_ADMIN_PRIVATE_KEY}
    volumes:
      - nginx-cache:/var/cache/nginx
      - nginx-logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  nginx-cache:
  nginx-logs: 